In [1]:
import numpy as np


In [2]:
import numpy as np

# Create a 2 by 3 matrix containing elements from 1 to 6
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Multiply the matrix by a scaler of two
scaled_matrix = 2 * matrix

print(scaled_matrix)


[[ 2  4  6]
 [ 8 10 12]]


In [4]:
# Create a 3 by 3 identity matrix
identity_matrix = np.identity(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#Creating a 1-D array containing elements ranging from zero to twenty-seven
arry1 = np.arange(0, 28)

# Reshape the 1-D array to a 3-D array
arry2 = arry1.reshape((3, 3, 3))

print(arry2)


ValueError: cannot reshape array of size 28 into shape (3,3,3)

In [5]:

# Creating the first 2-D array containing elements from 1 to 6
array1 = np.array([[1, 2, 3], [4, 5, 6]])

# Creating the second 2-D array containing elements from 7 to 12
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontally stack the two arrays together
horizontal_stack = np.hstack((array1, array2))

print(horizontal_stack)
# Vertically stack the two arrays together
vertical_stack = np.vstack((array1, array2))

print(vertical_stack)




[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# Creating an equally spaced sequence with a gap of 5 ranging from 0 to 100
sequence = np.arange(0, 101, 5)

print(sequence)


[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
